### ISSUE TITLE
Epic: Obtain gold verification for connector

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#155]
### Gate/Entrance Criteria:
_In order to begin this epic, the following item(s) must be completed)_
- [x] Access to Verification guide
- [x] Access to verification checklist
- [x] Alignment with PG and Confluent

#### What:
- [x] Apply for Confluent Verified Integrations Program
- [x] Review repo against latest version of the [verification guide](https://github.com/microsoft/kafka-connect-cosmosdb/files/5656227/20200325-VIP_Connect-Verification_Guide.pdf)
- [x] Complete the [verification checklist](https://github.com/microsoft/kafka-connect-cosmosdb/files/5656239/20200325-VIP_Connect-Verification_Checklist.pdf)
- [x] Complete the [self verification test results](https://github.com/microsoft/kafka-connect-cosmosdb/files/5656245/20200325-Self_Verification_Test_Results-Connect_Template.pdf)
- [x] Collaborate with Confluent to prepare connector for submission (addressing feedback items)

#### Why:
Gold verification affords us credibility and unlocks our ability to work with companies who require this status to run in production.

#### Who:
Developers in collaboration with developers from Confluent and from the Product Group

### Exit Criteria
- [ ] Connector has gained gold verification from Confluent
- [ ] Connector published to Confluent Hub

**Comment by brandynbrown** [comment]
@jkeane The self verification form also mentions stuff about testing (although minimally helpful) It might make sense for us to double check this stuff during the testing chat
