### ISSUE TITLE
Add meta-data to sink & source connector to allow origin identification

### ISSUE THREAD

**Issue by ryancrawcour** [microsoft/kafka-connect-cosmosdb#167]
**## Problem Statement**
When using the Cosmos DB Java client, the user-agent should be set to allow the data to be identified as coming from the Kafka Connect.

**## Proposed Solution**
Setting the user-agent string in the Cosmos DB Java client
follow the following convention for setting user-agent string - “APN/1.0 {CompanyName}/1.0 {ApplicationName}/{XX.X}”

CompanyName == Microsoft
ApplicationName == KafkaConnect

**## Alternative Solutions**
Might be nice to have metadata to the message being transferred in order to track data lineage. 
Further investigation is required for this. 

**## Additional context**
https://github.com/Azure/azure-cosmosdb-java/blob/ef35fdf0efcfbadedbd83c8831d1af90299e2edd/commons/src/main/java/com/microsoft/azure/cosmosdb/ConnectionPolicy.java#L211

## Next Steps
- [x] Team consensus to proceed 
- [x] Complete Design Review
- [ ] Schedule Design Session
