### ISSUE TITLE
Game Plan Review Checklist

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#198]
- [x] Update to milestones @brandynbrown 
- [x] Update straw man schedule @ryancrawcour 
- [ ] Review from Deanna/ @atxryan 
- [ ] Schedule internal dry run @brandynbrown 
- [ ] Schedule GPR @brandynbrown
