### ISSUE TITLE
Epic: Implement and investigate the enhancements backlog

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#271]
### Gate/Entrance Criteria:
_In order to begin this epic, the following item(s) must be completed)_
There is nothing required prior to beginning this epic.

#### What:
- [x] Refine existing enhancements backlog
- [x] Identify investigation points required to implement each request
- [x] Deliver streamlined enhancements backlog for PG

#### Why:
Prior to handing the connector over to the PG group for GA, we need to clean up the backlog of enhancements that have been requested by the community. While we have these resources, we should implement the items that are feasible and valuable.

#### Who:
Developers in collaboration with developers from Confluent and from the Product Group

### Exit Criteria
- [x] Any enhancements requested prior to 2/2/21 have been investigated / refined.
- [x] Any enhancements prior to 2/2/21 have either been implemented or are in a state for proper handoff post-project.
