### ISSUE TITLE
Epic: Product Group Handoff

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#272]
### Gate/Entrance Criteria:
_In order to begin this epic, the following item(s) must be completed)_
- [x] Connector is published to Confluent Hub
- [x] Connector has gold verification from Confluent.

#### What:
- [x] Guided code review with PG #275 _(Scheduled for 2/25)_
- [x] Team has discussed all blocked tickets with the PG _(Scheduled for 2/18)_

#### Why:
The PG will be taking over the connector for long-term support and enhancements. Therefore, it's important that we provide a proper handoff, including an overview of the code, status of the connector, and answer any lingering questions.

### Exit Criteria:
- [x] Developer documentation is complete and void of knowledge gaps, erroneous/outdated information based on what we know of the connector today.
- [x] Documented formal handoff and support plan
