### ISSUE TITLE
Sprint 5  (1/21 - 1/27)

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#284]
## Sprint Goal
Wrap up final requirements for gold verification and publish to Confluent. Submit for gold verification.

## Commitment
- [x] Bugs: [#233]
- [x] Publish to Confluent: [~#1~ Pulled] [~#204~]
- [x] Wrap Up Gold Reqs: [~#251~ Pulled] [#231]
- [x] Testing: [#227] [#242]
- [x] Refine: [#7] [#83] (_Review with PG to determine if we will do these_)

### Added to Sprint
_Ensure you list the justification for pulling anything into sprint. Ex: Prod outage, revenue impacts, dev bandwidth, etc._
- [x] #265 
    - Time Sensitive / Doesn't affect dev velocity
- [x] #246 
    - Small and required for gold; received after sprint start
- [x] #279  
    - Dev bandwidth
- [x] #253 
    - Dev bandwidth - swapped for #251

### Trade-offs
_If you're swapping tickets in, what tickets are falling out?_
- #251 (reasoning: address bugs before metrics)

## Notes
#1 was pulled - Needs further refinement and not required for gold
#204 we delivered the release and are waiting for publishing to Confluent Hub.
