### ISSUE TITLE
M1- Engineering Fundamentals Checklist - scheduled for 2/9

### ISSUE THREAD

**Issue by brandynbrown** [microsoft/kafka-connect-cosmosdb#299]
## Tech Lead's Engineering Fundamentals Checklist

This checklist helps to ensure that our projects meet our Engineering Fundamentals.

## Source Control

- [x] The main branch is locked.
- [x] Merges are done through PRs.
- [x] PRs reference related work items.
- [x] Commit history is consistent and commit messages are informative (what, why).
- [x] Secrets are not part of the commit history or made public. (see [Credential scanning](https://github.com/microsoft/code-with-engineering-playbook/tree/master/continuous-integration/credential-scanning/readme.md))
- [x] Public repositories follow the [OSS guidelines](https://github.com/microsoft/code-with-engineering-playbook/tree/master/source-control/readme.md#creating-a-new-repository), see `Required files in default branch for public repositories`.

More details on [Source Control](https://github.com/microsoft/code-with-engineering-playbook/tree/master/source-control/readme.md)

## Work Item Tracking

- [x] All items are tracked in AzDevOps (or similar).
- [x] The board is organized (swim lanes, feature tags, technology tags).

## Testing

- [x] Unit tests cover the majority of all components (>90% if possible).
- [x] Integration tests run to test the solution e2e.

More details on [Unit Testing](https://github.com/microsoft/code-with-engineering-playbook/tree/master/automated-testing/unit-testing/readme.md)

## CI/CD

- [x] Project runs CI with automated build and test on each PR.
- [x] Project uses CD to manage deployments to a replica environment before PRs are merged.
- [x] Main branch is always shippable.

## Security - TO DO

- [x] Access control.
- [x] Separation of concerns. (@ryancrawcour ?)
- [x] Robust treatment of secrets. (@ryancrawcour ?)
- [x] Encryption for data in transit (and if necessary at rest) and password hashing. (Should be handled by Kafka)

## Observability

- [x] Significant business and functional events are tracked and related metrics collected.
- [x] Application faults and errors are logged.
- [ ] Health of the system is monitored.
- [ ] The client and server side observability data can be differentiated.
- [x] Logging configuration can be modified without code changes (eg: verbose mode).
- [ ] [Incoming tracing context](https://github.com/microsoft/code-with-engineering-playbook/tree/master/observability/correlation-id.md) is propagated to allow for production issue debugging purposes.
- [x] GDPR compliance is ensured regarding PII (Personally Identifiable Information).

## Agile/Scrum

- [x] Process Lead (fixed/rotating) to run standup daily.
- [x] Agile process clearly defined within team.
- [x] Tech Lead (+ PO/Others) have responsibility for backlog management and refinement.
- [x] Working agreement between members of team and customer.

## Design Reviews

- [x] Process for conducting design reviews is included in the [Working Agreement](https://github.com/microsoft/code-with-engineering-playbook/tree/master/agile-development/team-agreements/working-agreements/readme.md)
- [ ] Design reviews for each major component of the solution are carried out and documented, including alternatives.
- [ ] Stories and/or PRs link to the design document.
- [ ] Each user story includes a task for design review by default, which is assigned or removed during sprint planning.
- [ ] Project advisors are invited to design reviews or asked to give feedback to the design decisions captured in documentation.
- [ ] Discover all the reviews that the customer's processes require and plan for them.

## Code Reviews

- [x] Clear agreement in the team as to function of code reviews.
- [ ] Code review checklist or established process.
- [x] A minimum number of reviewers (usually 2) for a PR merge is enforced by policy.
- [x] Linters/Code Analyzers, unit tests and successful builds for PR merges are set up.
- [x] Process to enforce a quick review turnaround.

More details on [Code Reviews](https://github.com/microsoft/code-with-engineering-playbook/tree/master/code-reviews/README.md)

## Retrospectives

- [x] Set time for retrospectives each week/at the end of each sprint.
- [x] 1-3 proposed experiments to be tried each week/sprint to improve the process.
- [x] Experiments have owners and are added to project backlog.
- [x] Longer retrospective for Milestones and project completion.

More details on [Retrospectives](https://github.com/microsoft/code-with-engineering-playbook/tree/master/agile-development/retrospectives/readme.md)

## Engineering Feedback

- [x] Submit business and technical blockers that prevent project success
- [x] Add suggestions for improvements to leveraged services and components
- [x] Ensure feedback is detailed and repeatable

More details on [Engineering Feedback](https://github.com/microsoft/code-with-engineering-playbook/tree/master/engineering-feedback/readme.md)

**Comment by brandynbrown** [comment]
- add plugin for code coverage analysis
- @ryancrawcour for design review, we didn't do any formal ones except for the testing plan (done today), did you do any with PG?
- @ryancrawcour observability section needs some love, team felt that this was largely NA for our project.

**Comment by ryancrawcour** [comment]
*   Not much needed in terms of design review as a lot of the design is dictated to us by either Kafka Connect, or Cosmos DB. We did do some design discussions with the PG where it made sense.
  *   Agree that observability is mostly NA for this project, besides the logging (which is in place
